build:
	protoc -I. --go_out=plugins=micro:./ proto/user/user.proto   # using go micro plugin
	GOOS=linux GOARCH=amd64		# no 'go build' here, building in container
	docker build -t user-service .

run:
	docker run -p 50052:50051 \
		-e MICRO_SERVER_ADDRESS=:50051 \
		-e MICRO_REGISTRY=mdns user-service
